[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
chrono = "0.4"
clap = "4"
log = "0.4"
serde = "1"
serde_yaml = "0.9"
shadow-rs = "0.27"
sqlx = "0.7"
time = "0.3"
thiserror = "1"
tokio = "1"
tokio-util = "0.7"
url = "2"
uuid = "1"
