[workspace]
resolver = "2"
members = [
    "axum-unix",
    "dmon",
    "fstore",
    "fstore-core",
    "fstored",
    "sql-helper-macros",
    "timber",
]

[workspace.dependencies]
chrono = "0.4"
clap = "4"
log = "0.4"
serde = "1"
serde_yaml = "0.9"
shadow-rs = "0.26"
sqlx = "0.7"
time = "0.3"
thiserror = "1"
tokio = "1"
uuid = "1"
