[package]
name = "fstore"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["serde"] }

# HTTP dependencies
bytes = { version = "1", optional = true }
futures-core = { version = "0.3", optional = true }
mime = { version = "0.3", optional = true }
reqwest = { version = "0.11", features = ["json", "stream"], optional = true }
tokio = { workspace = true, optional = true }
tokio-stream = { version = "0.1", optional = true }
tokio-util = { workspace = true, optional = true }
url = { workspace = true, features = ["serde"], optional = true }

[features]
http = [
    "dep:bytes",
    "dep:futures-core",
    "dep:mime",
    "dep:reqwest",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tokio-util",
    "dep:url",
]
