[package]
name = "fstore"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
