[package]
name = "fstore"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
time = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
