[package]
name = "fstore-core"
version = "0.1.0"
edition = "2021"

[dependencies]
base16ct = "0.2"
fstore = { path = "../fstore" }
libc = "0.2"
log = "0.4"
magic = "0.16"
sha2 = "0.10"
sql-helper-macros = { path = "../sql-helper-macros" }
sqlx = { workspace = true, features = [
    "macros",
    "postgres",
    "runtime-tokio",
    "time",
    "uuid",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
time = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
