[package]
name = "fstored"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
fstore-core = { path = "../fstore-core" }
serde = { workspace = true }
serde_yaml = "0.9"
